# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.5
  - 3.6
install: pip install -r requirements.txt
# before_script:
#   - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
#   - export FLASK_DEBUG=1

script: python application.py test